import { SignIn } from "@clerk/nextjs";
import Head from "next/head";
import Navbar from "@components/navbar";

const SignUpPage = () => (
    <>
        <Head>
            <title>Sing In | Glow Gang</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />

        <div className="mt-20 flex flex-col items-center justify-center">
            <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        </div>
    </>
);
export default SignUpPage;
