import { SignIn } from "@clerk/nextjs";
import Head from "next/head";
import Navbar from "@components/navbar";

const SignUpPage = () => (
    <>
        <Head>
            <title>Sign In | Glow Gang</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />

        <div className="mt-20 flex flex-col items-center justify-center">
            <SignIn
                path="/sign-in"
                routing="path"
                signUpUrl="/sign-up"
                redirectUrl="/auth/sso-callback"
                appearance={{
                    layout: {
                        socialButtonsVariant: "iconButton",
                        socialButtonsPlacement: "top"
                    }
                }}
            />
        </div>
    </>
);
export default SignUpPage;
