import { SignUp } from "@clerk/nextjs";
import Head from "next/head";
import Navbar from "utils,components/components/navbar";


const SignUpPage = () => (

    <>
        <Head>
            <title>Sign Up | Glow Gang</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />

        <div className="flex flex-col items-center justify-center mt-20">
            <SignUp path="/sign-up" routing="path" signInUrl="/sign-in" />
        </div>
       
    </>

);
export default SignUpPage;