import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import Hero from "../components/hero";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Glow Gang</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            <Hero />
        </>
    );
};

export default Home;
