import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import Hero from "../components/hero";
import { SignedIn, SignedOut } from "@clerk/nextjs";
import Dashboard from "./dashboard";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Glow Gang</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      
      <SignedOut>
        <Navbar />
        <Hero />
      </SignedOut>


      <SignedIn>
        <Dashboard />
      </SignedIn>





    </>
  );
};

export default Home;



